#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
sh /home/arik/dotfiles/bspwm/.config/bspwm/scripts/bspwm-xrandr-setup.sh &
picom --animations -b --config ~/.config/picom/picom.conf &
pkill dunst; dunst &
wal -R &
sh /home/arik/dotfiles/polybar/.config/polybar/launch.sh &
picom &
sh /home/arik/dotfiles/bspwm/.config/bspwm/scripts/startup-stuff.sh &
lxpolkit &



# Workspaces
bspc monitor DP-4 -d I II III
bspc monitor DP-1 -d V V VI
bspc monitor DP-2 -d VII VIII IX X

# Stuff
bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
