#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
picom --animations -b --config ~/.config/picom/picom.conf &
pkill dunst; dunst &
wal -R &
sh /home/arik/dotfiles/polybar/.config/polybar/launch.sh &
picom &
lxpolkit &
ckb-next -b &
#polychromatic-tray-applet &
sh ~/dotfiles/rgb/rgb.sh on &
#sh /home/arik/dotfiles/bspwm/.config/bspwm/scripts/bspwm-xrandr-setup.sh &
sh /home/arik/dotfiles/bspwm/.config/bspwm/scripts/startup-stuff.sh &



# Workspaces
bspc monitor HDMI-A-0 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII
bspc monitor DisplayPort-0 -d IX X
#bspc monitor DisplayPort-5 -d V V VI
#bspc monitor DisplayPort-6 -d VII VIII IX X

# Stuff
bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
